name: Tests

on:
  push:
    branches:
      - '**'
    tags:
      - '**'


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up GitHub Actions
      uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - name: Check if the repository is private
      run: exit 1
      if: ${{github.event.repository.private}}
    - name: Get testing lib
      run: set -eu && git clone --branch main --single-branch --depth 1 https://github.com/Yandex-Practicum/tests-selfmade-project-2-v2-public.git
    - name: Run the tests
      run: bash tests-selfmade-project-2-v2-public/run.sh
    - name: Upload layout-compare
      uses: actions/upload-artifact@v3
      with:
        name: layout-compare
        path: tests-selfmade-project-2-v2-public/output.jpg
    - name: Show test results
      run: bash tests-selfmade-project-2-v2-public/result.sh
